#!/bin/bash

# Test script for Claude integration in Brummer PTY

echo "Testing Claude PTY Integration"
echo "=============================="
echo ""
echo "This script will test if Claude can respond through the PTY terminal."
echo ""
echo "Prerequisites:"
echo "1. Make sure you have ANTHROPIC_API_KEY set"
echo "2. Build brummer: make build"
echo ""
echo "Test steps:"
echo "1. Start brummer: ./brum"
echo "2. Navigate to AI Coders view (press 8)"
echo "3. Start Claude in interactive mode: /ai claude"
echo "4. When the PTY terminal appears, press Enter to focus"
echo "5. Type: say hi"
echo "6. Press Enter"
echo ""
echo "Expected result:"
echo "- Claude should respond with a greeting"
echo "- The response should appear in the purple-bordered terminal"
echo ""
echo "Current status:"
echo "- Keyboard input: FIXED ✅"
echo "- ESC to unfocus: FIXED ✅"
echo "- Tab navigation disabled when focused: FIXED ✅"
echo "- Output display: DEBUGGING 🔍"
echo ""
echo "Debug notes:"
echo "- The purple frame is from Brummer (borderStyle with color 62)"
echo "- PTY output subscription is set up correctly"
echo "- The issue might be in the ProcessOutput method or buffer rendering"